#!/usr/bin/bash

DEBUG=""
if test "$1" = "-r"
then
    DEBUG="-g"
fi
gcc main.c list.c process_record.c string_utils.c logs.c process_runner.c -o main -w -lm $DEBUG
if test "$1" != "-r"
then
    ./main $1
    rm main
fi
